//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace ProcrastinHater.POCOEntities
{
    public partial class ProcrastinHaterEntities : ObjectContext
    {
        public const string ConnectionString = "name=ProcrastinHaterEntities";
        public const string ContainerName = "ProcrastinHaterEntities";
    
        #region Constructors
    
        public ProcrastinHaterEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ProcrastinHaterEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ProcrastinHaterEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<ChecklistElement> ChecklistElements
        {
            get { return _checklistElements  ?? (_checklistElements = CreateObjectSet<ChecklistElement>("ChecklistElements")); }
        }
        private ObjectSet<ChecklistElement> _checklistElements;
    
        public ObjectSet<DatabaseInfo> DatabaseInfoes
        {
            get { return _databaseInfoes  ?? (_databaseInfoes = CreateObjectSet<DatabaseInfo>("DatabaseInfoes")); }
        }
        private ObjectSet<DatabaseInfo> _databaseInfoes;
    
        public ObjectSet<PositionInformation> PositionInformations
        {
            get { return _positionInformations  ?? (_positionInformations = CreateObjectSet<PositionInformation>("PositionInformations")); }
        }
        private ObjectSet<PositionInformation> _positionInformations;

        #endregion
    }
}
