//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ProcrastinHater.POCOEntities
{
    public partial class CustomScheduleSpecifier
    {
        #region Primitive Properties
    
        public virtual int CustomScheduleID
        {
            get { return _customScheduleID; }
            set
            {
                if (_customScheduleID != value)
                {
                    if (CustomSchedule != null && CustomSchedule.ScheduleID != value)
                    {
                        CustomSchedule = null;
                    }
                    _customScheduleID = value;
                }
            }
        }
        private int _customScheduleID;
    
        public virtual int DayOfYear
        {
            get;
            set;
        }
    
        public virtual int Year
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CustomSchedule CustomSchedule
        {
            get { return _customSchedule; }
            set
            {
                if (!ReferenceEquals(_customSchedule, value))
                {
                    var previousValue = _customSchedule;
                    _customSchedule = value;
                    FixupCustomSchedule(previousValue);
                }
            }
        }
        private CustomSchedule _customSchedule;

        #endregion
        #region Association Fixup
    
        private void FixupCustomSchedule(CustomSchedule previousValue)
        {
            if (previousValue != null && previousValue.CustomScheduleSpecifiers.Contains(this))
            {
                previousValue.CustomScheduleSpecifiers.Remove(this);
            }
    
            if (CustomSchedule != null)
            {
                if (!CustomSchedule.CustomScheduleSpecifiers.Contains(this))
                {
                    CustomSchedule.CustomScheduleSpecifiers.Add(this);
                }
                if (CustomScheduleID != CustomSchedule.ScheduleID)
                {
                    CustomScheduleID = CustomSchedule.ScheduleID;
                }
            }
        }

        #endregion
    }
}
