//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ProcrastinHater.POCOEntities
{
    public partial class DayOfYearSpecifier
    {
        #region Primitive Properties
    
        public virtual int YearlyScheduleID
        {
            get { return _yearlyScheduleID; }
            set
            {
                if (_yearlyScheduleID != value)
                {
                    if (SchedulingInformation != null && SchedulingInformation.ScheduleID != value)
                    {
                        SchedulingInformation = null;
                    }
                    _yearlyScheduleID = value;
                }
            }
        }
        private int _yearlyScheduleID;
    
        public virtual int DayOfYear
        {
            get;
            set;
        }
    
        public virtual long TimeOfDayToStartTicks
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual SchedulingInformation SchedulingInformation
        {
            get { return _schedulingInformation; }
            set
            {
                if (!ReferenceEquals(_schedulingInformation, value))
                {
                    var previousValue = _schedulingInformation;
                    _schedulingInformation = value;
                    FixupSchedulingInformation(previousValue);
                }
            }
        }
        private SchedulingInformation _schedulingInformation;

        #endregion
        #region Association Fixup
    
        private void FixupSchedulingInformation(SchedulingInformation previousValue)
        {
            if (previousValue != null && previousValue.DayOfYearSpecifiers.Contains(this))
            {
                previousValue.DayOfYearSpecifiers.Remove(this);
            }
    
            if (SchedulingInformation != null)
            {
                if (!SchedulingInformation.DayOfYearSpecifiers.Contains(this))
                {
                    SchedulingInformation.DayOfYearSpecifiers.Add(this);
                }
                if (YearlyScheduleID != SchedulingInformation.ScheduleID)
                {
                    YearlyScheduleID = SchedulingInformation.ScheduleID;
                }
            }
        }

        #endregion
    }
}
