//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ProcrastinHater.POCOEntities
{
    public partial class DayofMonthSpecifier
    {
        #region Primitive Properties
    
        public virtual int MonthlyScheduleID
        {
            get { return _monthlyScheduleID; }
            set
            {
                if (_monthlyScheduleID != value)
                {
                    if (MonthlySchedule != null && MonthlySchedule.ScheduleID != value)
                    {
                        MonthlySchedule = null;
                    }
                    _monthlyScheduleID = value;
                }
            }
        }
        private int _monthlyScheduleID;
    
        public virtual int Day
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual MonthlySchedule MonthlySchedule
        {
            get { return _monthlySchedule; }
            set
            {
                if (!ReferenceEquals(_monthlySchedule, value))
                {
                    var previousValue = _monthlySchedule;
                    _monthlySchedule = value;
                    FixupMonthlySchedule(previousValue);
                }
            }
        }
        private MonthlySchedule _monthlySchedule;

        #endregion
        #region Association Fixup
    
        private void FixupMonthlySchedule(MonthlySchedule previousValue)
        {
            if (previousValue != null && previousValue.DayofMonthSpecifiers.Contains(this))
            {
                previousValue.DayofMonthSpecifiers.Remove(this);
            }
    
            if (MonthlySchedule != null)
            {
                if (!MonthlySchedule.DayofMonthSpecifiers.Contains(this))
                {
                    MonthlySchedule.DayofMonthSpecifiers.Add(this);
                }
                if (MonthlyScheduleID != MonthlySchedule.ScheduleID)
                {
                    MonthlyScheduleID = MonthlySchedule.ScheduleID;
                }
            }
        }

        #endregion
    }
}
