//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ProcrastinHater.POCOEntities
{
    public partial class Group : ChecklistElement
    {
        #region Primitive Properties
    
        public virtual bool IsExpanded
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<ChecklistElement> ChecklistElements
        {
            get
            {
                if (_checklistElements == null)
                {
                    var newCollection = new FixupCollection<ChecklistElement>();
                    newCollection.CollectionChanged += FixupChecklistElements;
                    _checklistElements = newCollection;
                }
                return _checklistElements;
            }
            set
            {
                if (!ReferenceEquals(_checklistElements, value))
                {
                    var previousValue = _checklistElements as FixupCollection<ChecklistElement>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupChecklistElements;
                    }
                    _checklistElements = value;
                    var newValue = value as FixupCollection<ChecklistElement>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupChecklistElements;
                    }
                }
            }
        }
        private ICollection<ChecklistElement> _checklistElements;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupChecklistElements(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ChecklistElement item in e.NewItems)
                {
                    item.ParentGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ChecklistElement item in e.OldItems)
                {
                    if (ReferenceEquals(item.ParentGroup, this))
                    {
                        item.ParentGroup = null;
                    }
                }
            }
        }

        #endregion
    }
}
