//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ProcrastinHater.POCOEntities
{
    public partial class HardSettings
    {
        #region Primitive Properties
    
        public virtual int NextChecklistElementsKey
        {
            get;
            set;
        }
    
        public virtual int DaysOfHistoryToShow
        {
            get;
            set;
        }
    
        public virtual bool Check
        {
            get;
            set;
        }
    
        public virtual int NextTimedTaskSettingsKey
        {
            get;
            set;
        }

        #endregion
    }
}
