//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ProcrastinHater.POCOEntities
{
    public partial class MonthlyRelativeSchedule : SchedulingInformation
    {
        #region Navigation Properties
    
        public virtual ICollection<MonthlyRelativeSpecifier> MonthlyRelativeSpecifiers
        {
            get
            {
                if (_monthlyRelativeSpecifiers == null)
                {
                    var newCollection = new FixupCollection<MonthlyRelativeSpecifier>();
                    newCollection.CollectionChanged += FixupMonthlyRelativeSpecifiers;
                    _monthlyRelativeSpecifiers = newCollection;
                }
                return _monthlyRelativeSpecifiers;
            }
            set
            {
                if (!ReferenceEquals(_monthlyRelativeSpecifiers, value))
                {
                    var previousValue = _monthlyRelativeSpecifiers as FixupCollection<MonthlyRelativeSpecifier>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMonthlyRelativeSpecifiers;
                    }
                    _monthlyRelativeSpecifiers = value;
                    var newValue = value as FixupCollection<MonthlyRelativeSpecifier>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMonthlyRelativeSpecifiers;
                    }
                }
            }
        }
        private ICollection<MonthlyRelativeSpecifier> _monthlyRelativeSpecifiers;

        #endregion
        #region Association Fixup
    
        private void FixupMonthlyRelativeSpecifiers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MonthlyRelativeSpecifier item in e.NewItems)
                {
                    item.MonthlyRelativeSchedule = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MonthlyRelativeSpecifier item in e.OldItems)
                {
                    if (ReferenceEquals(item.MonthlyRelativeSchedule, this))
                    {
                        item.MonthlyRelativeSchedule = null;
                    }
                }
            }
        }

        #endregion
    }
}
