//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ProcrastinHater.POCOEntities
{
    public partial class Task : ChecklistElement
    {
        #region Primitive Properties
    
        public virtual string Details
        {
            get;
            set;
        }
    
        public virtual int Status
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DueTime
        {
            get;
            set;
        }

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;

        #endregion
    }
}
