//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ProcrastinHater.POCOEntities
{
    public partial class TimeoutAction
    {
        #region Primitive Properties
    
        public virtual int TimeoutActionID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<TimedTaskSetting> TimedTaskSettings
        {
            get
            {
                if (_timedTaskSettings == null)
                {
                    var newCollection = new FixupCollection<TimedTaskSetting>();
                    newCollection.CollectionChanged += FixupTimedTaskSettings;
                    _timedTaskSettings = newCollection;
                }
                return _timedTaskSettings;
            }
            set
            {
                if (!ReferenceEquals(_timedTaskSettings, value))
                {
                    var previousValue = _timedTaskSettings as FixupCollection<TimedTaskSetting>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTimedTaskSettings;
                    }
                    _timedTaskSettings = value;
                    var newValue = value as FixupCollection<TimedTaskSetting>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTimedTaskSettings;
                    }
                }
            }
        }
        private ICollection<TimedTaskSetting> _timedTaskSettings;

        #endregion
        #region Association Fixup
    
        private void FixupTimedTaskSettings(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (TimedTaskSetting item in e.NewItems)
                {
                    item.TimeoutAction = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TimedTaskSetting item in e.OldItems)
                {
                    if (ReferenceEquals(item.TimeoutAction, this))
                    {
                        item.TimeoutAction = null;
                    }
                }
            }
        }

        #endregion
    }
}
